apiVersion: v1
kind: Service
metadata:
  name: server-forwarder-service
spec:
  selector:
    app: python-docker
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-docker
spec:
  selector:
    matchLabels:
      app: python-docker
  replicas: 4
  template:
    metadata:
      labels:
        app: python-docker
    spec:
      containers:
      - name: python-docker
        image: lstevens/test:latest
        ports:
        - containerPort: 8080